[package]
name = "aidoku-multisource"
version = "0.1.0"
edition = "2021"
description = "Aidoku multi-source extension starting with mangabuddy.com"

[lib]
crate-type = ["cdylib"]

[dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs", branch = "next", package = "aidoku" }
